apiVersion: v1
kind: Pod
metadata:
  labels:
    app: load
  name: load
spec:
  containers:
  - image: qarlm/ghz
    name: load
    args:
    - --insecure
    - --call
    - helloworld.Greeter.SayHello
    - -d
    - '{"name": "john"}'
    - --duration=5m
    - --concurrency=100
    - --qps=200
    - --duration-stop=wait
    - workload:50051
    resources:
      requests:
        memory: "500Mi"
        cpu: "4"
      limits:
        memory: "500Mi"
        cpu: "4"
  restartPolicy: Never

