apiVersion: v1
kind: Pod
metadata:
  labels:
    app: workload
  name: workload
spec:
  containers:
  - image: sckmkny/hello-threads-node:0.1.0
    name: workload
    ports:
    - name: grpc
      containerPort: 50051
    resources:
      requests:
        memory: "500Mi"
        cpu: "2"
      limits:
        memory: "500Mi"
        cpu: "2"

